name: JSON extract
description: Extracts information from a JSON string

inputs:
  json:
    description: The JSON string to extract information from
    required: true
  paths:
    description: The paths or path to extract from the JSON string (e.g. '["path.to.value"]')
    required: true
  keys:
    description: The keys to output the extracted values (e.g. '["value1", "value2"]')
    required: false
    default: '[]'

outputs:
  values:
    description: The extracted values
    value: ${{ steps.extract-json.outputs }}

runs:
  using: composite
  steps:
    - name: Extract JSON
      id: extract-json
      uses: actions/github-script@v7
      with:
        script: |
          function normalizeValues(values) {
            if (Array.isArray(values)) {
              return values.map((value) => value.toString());
            } else {
              return [values.toString()];
            }
          }

          const goals = normalizeValues(JSON.parse("${{ inputs.paths }}"));
          const keys = normalizeValues(JSON.parse("${{ inputs.keys }}"));

          try {
            const json = JSON.parse("${{ inputs.json }}");

            goals.forEach((goal, index) => {
              const value = goal.split(".").reduce((acc, key) => acc[key], json);

              core.setOutput(keys[index] ?? `path-${index}`, value);
            });
          } catch (error) {
            core.error("Error while parsing the JSON");
            core.setFailed(error);
          }